// The drawer agent's way to object tracking (PureCut): `trackCutObject` asks
// the person to track something, `getCutTrackStatus` says what came of it.
// The agent never runs a model and never sees the video; it names a clip, a
// point it believes the subject is at, and what the mask is for. The app opens
// the Object mask tool on that clip with the point shown as a suggestion, and
// the person clicks, agrees to the model's download if needed, and confirms.
// Tracking then runs on this computer, in the app.

import { parseSource } from "@diffusionstudio/jsx";
import { authoredElement } from "@diffusionstudio/reconciler";
import { Computed, FrameRate, Name, Source, findGeometryAsset, getActiveEntity, getSceneAncestor } from "@diffusionstudio/runtime";
import { requireEditorSession } from "@/dapi/session";
import { isLooped } from "@/engine/editor";
import { containsLocked } from "@/engine/locking";
import {
  getObjectTrack,
  getVideoRect,
  isObjectMaskUse,
  objectMaskModelLoad,
  openTrackRequest,
  pendingTrackRequest,
  requestSubject,
  textsAboveClip,
  trackRequest,
  useLabel,
} from "@/engine/object-mask";
import type { Entity } from "koota";
import type { ObjectMaskUse, TrackRequest } from "@/engine/object-mask";

type TrackArgs = { clip?: unknown; at?: unknown; time?: unknown; use?: unknown; label?: unknown };

function fail(message: string): never {
  throw Error(message);
}

/**
 * Opens the Object mask tool for the person on `clip`, with the agent's point
 * as a suggestion and its use picked. Returns at once: nothing has changed.
 */
export function trackCutObject(args: TrackArgs = {}) {
  const { world } = requireEditorSession();

  const stamp = typeof args.clip === "string" ? args.clip.trim() : "";
  const parsed = stamp ? parseSource(stamp) : undefined;
  if (parsed?.file !== "index.tsx" || typeof parsed.locator !== "string")
    fail('Name the clip as "index.tsx:<id>", a video clip id from getCutContext.');
  const matches = world.query(Source).filter(entity => entity.isAlive() && entity.get(Source)?.value === stamp);
  if (matches.length === 0) fail(`There is no ${stamp} in the open project. Read getCutContext for the clip ids (objectMasks lists video clips by id).`);
  if (matches.length > 1) fail(`${stamp} is generated by a loop. Object tracking needs a directly authored clip.`);
  const clip = matches[0]!;
  if (!authoredElement(clip) || isLooped(clip)) fail(`${stamp} is not directly authored (it comes from a loop). Object tracking needs a directly authored clip.`);
  if (containsLocked(world, clip)) fail(`${stamp} is locked. Ask the person to unlock it before tracking an object in it.`);
  const rect = getVideoRect(world, clip);
  if (!rect) fail(`${stamp} is not a video clip. Objects can only be tracked in a clip that plays video (a rect with a videoPaint).`);

  const scene = getSceneAncestor(clip);
  if (!scene || scene !== getActiveEntity(world))
    fail(`${stamp} is in a scene that is not open on the timeline. Ask the person to open that scene first.`);

  let point: { x: number; y: number } | null = null;
  if (args.at !== undefined) {
    const at = args.at as { x?: unknown; y?: unknown } | null;
    const inside = (value: unknown) => typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 1;
    if (!at || typeof at !== "object" || !inside(at.x) || !inside(at.y))
      fail("`at` is a point in the clip's video frame: {x, y}, each 0 to 1 from the top left.");
    point = { x: at.x as number, y: at.y as number };
  }

  const fps = world.get(FrameRate)?.value || 30;
  const computed = clip.get(Computed);
  const start = computed?.start ?? 0;
  const end = computed?.end ?? start;
  const seconds = (frame: number) => Math.round((frame / fps) * 100) / 100;
  let frame: number;
  if (args.time !== undefined) {
    if (typeof args.time !== "number" || !Number.isFinite(args.time) || args.time < 0) fail("`time` is seconds on the scene's timeline, 0 or more.");
    frame = Math.round((args.time as number) * fps);
    if (frame < start || frame >= end)
      fail(`${stamp} plays from ${seconds(start)}s to ${seconds(end)}s on the timeline; ${args.time}s is outside it.`);
  } else {
    const playhead = scene.get(Computed)?.localTime ?? 0;
    frame = playhead >= start && playhead < end ? playhead : start;
  }

  const use: ObjectMaskUse = args.use === undefined ? "cutout" : isObjectMaskUse(args.use)
    ? args.use
    : fail('`use` is one of "cutout", "blur", "pixelate" or "behind".');
  if (use === "behind" && textsAboveClip(world, clip).length === 0)
    fail(`"behind" puts the texts above ${stamp} behind the subject, and there is none above it that plays at the same time. Add the text first (proposeCutSource), or ask for another use.`);

  let label: string | null = null;
  if (args.label !== undefined) {
    if (typeof args.label !== "string") fail("`label` is a short name for the object, such as \"his face\".");
    label = (args.label as string).replace(/\s+/g, " ").trim().slice(0, 60) || null;
  }

  const request = openTrackRequest(world, { clip, clipSource: stamp, clipName: clipName(world, clip), point, frame, use, label });
  return {
    status: "awaiting_person",
    request: request.id,
    clip: stamp,
    use,
    message:
      `Nothing has changed yet. PureCut opened the Object mask tool on ${stamp}${point ? " with your point marked as a suggestion" : ""}. ` +
      "Tell the person to click the subject (or use the suggested point), adjust it if needed and choose Confirm; " +
      "if the tracking model is not on this computer yet, they choose whether to download it. " +
      "Tracking runs in the app on this computer. Call getCutTrackStatus once they say they are done; do not call trackCutObject again meanwhile.",
  };
}

/** What became of the latest request, in words the agent can pass on. */
export function getCutTrackStatus() {
  const current = trackRequest();
  if (!current) return { status: "none", message: "No object tracking has been requested in this session." };
  const base = describe(current);
  if (current.status !== "pending") return base;

  const load = objectMaskModelLoad();
  const track = getObjectTrack();
  const prompted = track?.clip === current.clip;
  const waitingFor =
    load?.phase === "needs-download" && !prompted ? "download-consent"
      : load?.phase === "download" || load?.phase === "compile" ? "model-download"
        : prompted && (track!.status === "tracking" || track!.status === "saving") ? "tracking"
          : prompted && track!.status === "seeded" ? "confirm"
            : "click";
  const words: Record<typeof waitingFor, string> = {
    "download-consent": "The person has not yet agreed to download the tracking model; the Object mask bar is asking them.",
    "model-download": "The tracking model is downloading to this computer.",
    tracking: `Tracking is running on this computer (${track?.completed ?? 0} of ${track?.masks.length ?? 0} frames).`,
    confirm: "The person has picked the object and has not confirmed yet.",
    click: "The person has not clicked the subject yet.",
  };
  return {
    ...base,
    waitingFor,
    ...(load?.phase === "error" ? { modelError: load.error } : {}),
    message: `${words[waitingFor]} Nothing has changed in the project yet. Do not ask again; wait for the person.`,
  };
}

function describe(current: TrackRequest) {
  return {
    status: current.status,
    request: current.id,
    clip: current.clipSource,
    subject: requestSubject(current),
    askedUse: current.use,
    ...(current.result
      ? {
          mask: current.result.mask,
          use: current.result.use,
          applied: current.result.applied,
          ...(current.result.use !== current.use ? { note: `The person chose ${useLabel(current.result.use)} instead of ${useLabel(current.use)}.` } : {}),
          next: "Read getCutContext: the mask is in objectMasks and the source already has the effect. Use proposeCutSource or proposeCutEdits with that mask path to adjust it; do not track again.",
        }
      : {}),
    message: current.reason ?? "",
  };
}

function clipName(world: ReturnType<typeof requireEditorSession>["world"], clip: Entity): string {
  const name = clip.get(Name)?.value;
  if (name) return name;
  const footage = findGeometryAsset(world, clip);
  return footage ? footage.path.split("/").pop()!.replace(/\.[^.]+$/, "") : "this clip";
}

/** Whether a request is waiting for the person: the drawer reports it in getCutContext. */
export function pendingTrackSummary() {
  const current = pendingTrackRequest();
  return current ? { request: current.id, clip: current.clipSource, subject: requestSubject(current), use: current.use } : null;
}
